---
version: "2"
plugins:
  bandit:
    enabled: true
  markdownlint:
    checks:
      MD002:
        enabled: false
    enabled: true
  pylint:
    enabled: true
  pep8:
    enabled: true
checks:
  method-lines:
    config:
      threshold: 100
