language: python
python: "3.7.5"
os: linux
dist: xenial

# To override installing requirements always
install: pip --version

services:
  - docker

before_install:
  - docker build . -t pyghost:v1.0
  - docker run -ti pyghost:v1.0 screenfetch
  - sudo apt-get install screenfetch
  - screenfetch

jobs:
  include:
    - name: Run Python Tests
      script: docker run -ti pyghost:v1.0 pytest

    - name: CodeCov Metrics
      script: docker run -ti pyghost:v1.0 pytest --cov-report=xml --cov=pyGhost tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: agi.uqbar@gmail.com
