language: python
os: linux
dist: xenial

services:
  - docker

before_install:
  - docker build . -t pyghost:v1.0
  - docker run -ti pyghost:v1.0 pytest
  #- docker run -ti pyghost:v1.0 bash
  #- docker run -ti pyghost:v1.0 "pytest"
  #- screenfetch

script:
  - pytest && flake8

notifications:
  email: agi.uqbar@gmail.com
