language: python
python: "3.7.5"
os: linux
dist: xenial

# To override installing requirements always
install: pip --version

services:
  - docker

before_install:
  - docker load -i docker_images/images.tar || true
  - docker build . -t pyghost:v1.0
  - docker run -ti pyghost:v1.0 screenfetch
  - sudo apt-get install screenfetch
  - screenfetch
  - pip install coverage

jobs:
  include:
    - name: Run Python Tests
      script: docker run -ti pyghost:v1.0 pytest

    - name: CodeCov Metrics
      install: pip install pytest-cov
      script: py.test --cov-report=xml --cov=myproj tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - docker_images

before_cache:
- docker save -o docker_images/images.tar $(docker images -a -q)

notifications:
  email: agi.uqbar@gmail.com
