language: python
python: "3.7.5"
os: linux
dist: xenial

# To override installing requirements always
install: pip --version

services:
  - docker

before_install:
  - docker build . -t pyghost:v1.0
  - docker run -ti pyghost:v1.0 screenfetch
  - apt-get install screenfetch
  - screenfetch

jobs:
  include:
    - name: Run Python Tests
      script: docker run -ti pyghost:v1.0 pytest

notifications:
  email: agi.uqbar@gmail.com
