language: python
python: "3.7.5"
os: linux
dist: xenial

# To override installing requirements always
install: pip --version

services:
  - docker

before_install:
  - docker build . -t pyghost:v1.0
  - docker run -ti pyghost:v1.0 screenfetch
  - sudo apt-get install screenfetch
  - screenfetch

jobs:
  include:
    - name: PyTest With Coverage
      script: docker run -ti pyghost:v1.0 pytest --cov-report=xml --cov=pyGhost tests/

after_success:
  - docker run -ti pyghost:v1.0 codecov
#  - docker run -ti pyghost:v1.0 bash <(curl -s https://codecov.io/bash)
#  - docker run -ti pyghost:v1.0 bash -c "curl -s https://codecov.io/bash | bash"


notifications:
  email: agi.uqbar@gmail.com
