language: python

services:
  - docker

before-install:
  - docker build . -t pyghost:v1.0
  - docker run -ti pyghost:v1.0 bash
  #- docker run -ti pyghost:v1.0 "pytest"
  #- docker run -ti pyghost:v1.0 "pwd; cd /app; pytest; flake8"

script:
  - pytest && flake8
#  - pytest && flake8

notifications:
  email: agi.uqbar@gmail.com
