language: python

services:
  - docker

before-install:
- docker build . -t pyGhost:v1.0
- docker run -ti pyGhost:v1.0 "cd /app; pytest; flake8"

script:
  - pytest && flake*

notifications:
  email: agi.uqbar@gmail.com
